### ISSUE TITLE
FileNotFoundError: cdxev/auxiliary/schema/spdx.schema.json

### ISSUE THREAD

**Issue by dleonard0** [Festo-se/cyclonedx-editor-validator#104]
I did `pip install cyclonedx-editor-validator` then `cdx-ev validate /tmp/sbom.json` on Ubuntu 23.10 and get
```
Traceback (most recent call last):
  File "/home/davidl/.local/bin/cdx-ev", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/davidl/.local/lib/python3.11/site-packages/cdxev/__main__.py", line 40, in main
    return args.cmd_handler(args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidl/.local/lib/python3.11/site-packages/cdxev/__main__.py", line 604, in invoke_validate
    if validate_sbom(
       ^^^^^^^^^^^^^^
  File "/home/davidl/.local/lib/python3.11/site-packages/cdxev/validator/validate.py", line 41, in validate_sbom
    load_spdx_schema(), specification=DRAFT202012
    ^^^^^^^^^^^^^^^^^^
  File "/home/davidl/.local/lib/python3.11/site-packages/cdxev/validator/helper.py", line 49, in load_spdx_schema
    with open("cdxev/auxiliary/schema/spdx.schema.json", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'cdxev/auxiliary/schema/spdx.schema.json'
```

The spdx.schema.json file is there in the site-packages directory though:

```
$ python --version
Python 3.11.6
$ pip --version
pip 23.0.1 from /home/davidl/.local/lib/python3.11/site-packages/pip (python 3.11)
$ python --version
Python 3.11.6
$ cdx-ev --version
0.9.1
$ find ~/.local/lib/ | grep spdx.schema
/home/davidl/.local/lib/python3.11/site-packages/cdxev/auxiliary/schema/spdx.schema.json
```

Workaround is to `cd /home/davidl/.local/lib/python3.11/site-packages/` first :)

**Comment by italvi** [comment]
@dleonard0 thanks for your report. This was resolved in #105 and released in v0.9.2 today.
